apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  containers:
  - name: cpu-stress
    image: busybox
    command: ["sh", "-c", "while true; do :; done"]
    resources:
      requests:
        cpu: "500m"
      limits:
        cpu: "1000m"

